//
//  UIColor+LCAdditions.h
//
//  Generated by Zeplin on 4/11/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIColor (LCAdditions)

+ (UIColor *)lc_jadeGreenColor;
+ (UIColor *)lc_lightSageColor;
+ (UIColor *)lc_peachyPinkColor;
+ (UIColor *)lc_jadeGreenTwoColor;
+ (UIColor *)lc_darkSkyBlueColor;
+ (UIColor *)lc_greyishColor;
+ (UIColor *)lc_pinkishGreyColor;

@end
