//
//  UIColor+LCAdditions.m
//
//  Generated by Zeplin on 4/11/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIColor+LCAdditions.h"

@implementation UIColor (LCAdditions)

+ (UIColor *)lc_jadeGreenColor {
	return [UIColor colorWithRed:41.0f / 255.0f green:181.0f / 255.0f blue:100.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)lc_lightSageColor {
	return [UIColor colorWithRed:178.0f / 255.0f green:234.0f / 255.0f blue:183.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)lc_peachyPinkColor {
	return [UIColor colorWithRed:249.0f / 255.0f green:131.0f / 255.0f blue:131.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)lc_jadeGreenTwoColor {
	return [UIColor colorWithRed:43.0f / 255.0f green:181.0f / 255.0f blue:101.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)lc_darkSkyBlueColor {
	return [UIColor colorWithRed:52.0f / 255.0f green:152.0f / 255.0f blue:219.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)lc_greyishColor {
	return [UIColor colorWithWhite:169.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)lc_pinkishGreyColor {
	return [UIColor colorWithWhite:208.0f / 255.0f alpha:1.0f];
}

@end
