//
//  UIFont+LCAdditions.m
//
//  Generated by Zeplin on 4/11/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import "UIFont+LCAdditions.h"

@implementation UIFont (LCAdditions)

+ (UIFont *)lc_textStyleFont {
	return [UIFont fontWithName:@"OpenSans" size:24.0f];
}

@end
