//
//  UIFont+LCAdditions.h
//
//  Generated by Zeplin on 4/11/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

#import <UIKit/UIKit.h>

@interface UIFont (LCAdditions)

+ (UIFont *)lc_textStyleFont;

@end
